on:
  push:
    branches:
    - feature/*

env:
  NODE_VERSION: '16.x'

jobs:
  integrate:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    - name: Run unit tests
      run: yarn test:unit
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    - name: Docker build
      run: docker build -t auth-app-frontend:snyk .
    - name: Run Snyk scan
      continue-on-error: true
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: auth-app-frontend:snyk
        args: --file=Dockerfile
    - name: Upload Snyk results to GitHub
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: snyk.sarif