on:
  push:
    branches:
    - feature/*

env:
  APP_NAME: auth-app-frontend
  AZURE_WEBAPP_NAME: azwe-frontend-d01-auth

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: development
    steps:
    - name: Git checkout
      uses: actions/checkout@v2
    - name: Docker login
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - name: Create .env file
      run: |
        cat << EOF >> .env
        NODE_ENV = development
        VUE_APP_BACKEND_URL = ${{ secrets.BACKEND_URL }}
        EOF
    - name: Docker build
      run: |
        docker build -t ${{ secrets.REGISTRY_SERVER }}/${{ env.APP_NAME }}:${{ github.sha }} .
    - name: Docker push
      run: |
        docker push ${{ secrets.REGISTRY_SERVER }}/${{ env.APP_NAME }}:${{ github.sha }}
    - name: 'Az login'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Deploy
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.APP_NAME }}
        images: '${{ secrets.REGISTRY_SERVER }}/${{ env.APP_NAME }}:${{ github.sha }}'
    - name: Az logout
      run: |
        az logout
